- name: Docker activity
  hosts: worker
  remote_user: kevin
  roles:
    - role: docker-find-container-by-image
      container_search_param: blunet-minecraft-volume-interface


  tasks:
  - name: asdfafsd
    debug: 
      msg: "asdfafd"
