---
- name: Get infos on container
  community.docker.docker_container_info:
    name: blunet-minecraft-volume-interface
  register: result

- name: Does container exist?
  ansible.builtin.debug:
    msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

- name: Print information about container
  ansible.builtin.debug:
    var: result.container
  when: result.exists

