---
- name: Get infos on container
  community.docker.docker_host_info:
    containers: true
  register: result

- name: Print information about containers
  ansible.builtin.debug:
    msg: "{{ (result.containers | selectattr('Names')) }}"
  when: result is defined

