---
- name: Create backup for blunet-minecraft-vanilla
  hosts: manager
  remote_user: pi

  tasks:
    - name: Check for compute node context
      ansible.builtin.shell:
        cmd: if [[ -z $(docker context ls | awk '{print $1}' | grep "{{ deployment.node }}") ]]; then echo true; else echo false; fi
      register: context_missing

    - name: Create missing docker context
      ansible.builtin.shell:
        cmd: docker context create {{ deployment.node }} --description "{{ deployment.node }}" --docker "host=ssh://kevin@{{ deployment.node }}"
      when: context_missing == "true"
    
    - name: Use new context
      command: docker context use {{ deployment.node }}

    - name: Find minecraft image name
      ansible.builtin.shell:
        cmd: docker ps --format json | jq -r ".Names" | grep "{{ deployment.name }}_minecraft-spigot-vanilla"
      register: minecraft_image_name

    - name: Execute backup command on container
      ansible.builtin.shell:
        cmd: docker exec "{{minecraft_image_name.stdout}}" mc_send backup default
        
    - name: Pause for 30 seconds for backup to complete
      ansible.builtin.pause:
        seconds: 30

    - name: Find s3 image name
      ansible.builtin.shell:
        cmd: docker ps --format json | jq -r ".Names" | grep "{{ deployment.name }}_world-backup"
      register: s3_image_name

    - name: Execute backup command on container
      ansible.builtin.shell:
        cmd: docker exec "{{s3_image_name.stdout}}" ./backup-and-cleanup.sh

    - name: Return to default context
      ansible.builtin.shell:
        cmd: docker context use default

