---
- name: Create backup for blunet-minecraft-vanilla
  hosts: manager
  remote_user: pi

  tasks:
    - name: Check for compute node context
      ansible.builtin.shell:
        cmd: if [[ -z $(docker context ls | awk '{print $1}' | grep "lovelace") ]]; then echo true; else echo false; fi
      register: context_missing

    - name: Create missing docker context
      ansible.builtin.shell:
        cmd: docker context create lovelace --description "lovelace" --docker "host=ssh://lovelace"
      when: context_missing == "true"
    
    - name: Use new context
      command: docker context use lovelace

    - name: Find minecraft image name
      ansible.builtin.shell:
        cmd: docker ps --format json | jq -r ".Names" | grep "blunet-minecraft-vanilla_minecraft-spigot-vanilla"
      register: minecraft_image_name

    - name: Execute backup command on container
      ansible.builtin.shell:
        cmd: docker exec "{{minecraft_image_name.stdout}}" mc_send backup take everything

    - name: Find s3 image name
      ansible.builtin.shell:
        cmd: docker ps --format json | jq -r ".Names" | grep "blunet-minecraft-vanilla_world-backup"
      register: s3_image_name

    - name: Execute backup command on container
      ansible.builtin.shell:
        cmd: docker exec "{{s3_image_name.stdout}}" ./backup-and-cleanup.sh

    - name: Return to default context
      ansible.builtin.shell:
        cmd: docker context use default

