---
- name: Deploy blunet-minecraft-vanilla
  hosts: manager
  remote_user: pi

  tasks:
    - name: Deploy blunet-minecraft-vanilla
      community.docker.docker_stack:
        state: present
        name: blunet-minecraft-vanilla
        compose:
          - /opt/blunet-minecraft/blunet-minecraft.docker-compose.yml
    - name: Notify discord of service being up
      uri: 
         url: "{{ blunet_notify_minecraft }}"
         method: POST
         body: "{\"content\": \"blunet-minecraft-vanilla service is UP.\"}"
         body_format: json
         status_code: [200, 202, 204]
         headers:
           Content-Type: "application/json"
           Accept: "application/json"
