- name: Destroy world
  hosts: worker
  remote_user: kevin
  roles:
    #returns "container_name"
    - role: docker-find-container-by-image
      container_search_param: blunet-minecraft-vanilla_volume-interface
    - role: docker-warn-container-stop

  tasks:
  - name: Run destroy world data script
    community.docker.docker_container_exec:
      container: "{{ container_name }}"
      command: destroy-location /minecraft/world
    register: result

  - name: Print stdout
    debug:
      var: result.stdout

  - name: Run destroy world_nether data script
    community.docker.docker_container_exec:
      container: "{{ container_name }}"
      command: destroy-location /minecraft/world_nether
    register: result

  - name: Print stdout
    debug:
      var: result.stdout

  - name: Run destroy world_the_end data script
    community.docker.docker_container_exec:
      container: "{{ container_name }}"
      command: destroy-location /minecraft/world_the_end
    register: result

  - name: Print stdout
    debug:
      var: result.stdout
