- name: Restore backup
  hosts: worker
  remote_user: kevin
  roles:
    - role: docker-find-container-by-image
      container_search_param: blunet-minecraft-volume-interface

  tasks:
  - name: Print backup name
    debug:
      var: s3_backup

  - name: Restore world
    community.docker.docker_container_exec:
      container: "{{ container_name }}"
      command: restore-backup "{{ s3_backup }}" /minecraft/world "{{ minecraft_uid }}"
    register: result

  - name: Print return code
    debug:
      var: result.rc

  - name: Exit if error
      meta: end_play
      when: result.rc == 1

  - name: Restore world_nether
    community.docker.docker_container_exec:
      container: "{{ container_name }}"
      command: restore-backup "{{ s3_backup }}" /minecraft/world_nether "{{ minecraft_uid }}"
    register: result

  - name: Print return code
    debug:
      var: result.rc

  - name: Exit if error
      meta: end_play
      when: result.rc == 1

  - name: Restore world_the_end
    community.docker.docker_container_exec:
      container: "{{ container_name }}"
      command: restore-backup "{{ s3_backup }}" /minecraft/world_the_end "{{ minecraft_uid }}"
    register: result

  - name: Print return code
    debug:
      var: result.rc
      
  - name: Exit if error
      meta: end_play
      when: result.rc == 1

  - name: Remove any existing backups
    community.docker.docker_container_exec:
      container: "{{ container_name }}"
      command: sh -c "rm /mc-backups/backups/world/*"
    register: result

  - name: Print return code
    debug:
      var: result.rc
