- name: Restore backup
  hosts: worker
  remote_user: kevin
  roles:
    - role: docker-find-container-by-image
      container_search_param: blunet-minecraft-volume-interface

  tasks:
  - name: Run restore script
    community.docker.docker_container_exec:
      container: "{{ container_name }}"
      command: restore-backup "{{ s3_backup }}" /minecraft/world-data
    register: result

  - name: Print stdout
    debug:
      var: result.stdout
