---
- name: Restore backup for blunet-minecraft-vanilla
  hosts: manager
  remote_user: pi
  vars:
    compute_context_name: lovelace
    minecraft_service_name: blunet-minecraft-vanilla_minecraft-spigot-vanilla
    minecraft_container_search_name: blunet-minecraft-vanilla_minecraft-spigot-vanilla
    s3_container_search_name: blunet-minecraft-vanilla_world-backup
    minecraft_container_volume_name: blunet-minecraft-vanilla_minecraft

  tasks:
    - name: Check for backup timestamp specified
      meta: end_play
      when: backup_timestamp is not defined

    - name: Check for compute node context
      ansible.builtin.shell:
        cmd: if [[ -z $(docker context ls | awk '{print $1}' | grep "{{ compute_context_name }}") ]]; then echo true; else echo false; fi
      register: context_missing

    - name: Create missing docker context
      ansible.builtin.shell:
        cmd: docker context create {{ compute_context_name }} --description "{{ compute_context_name }}" --docker "host=ssh://kevin@{{ compute_context_name }}"
      when: context_missing == "true"

    - name: Scale down minecraft service
      ansible.builtin.shell:
        cmd: docker service scale {{ minecraft_service_name }}=0
    
    - name: Use new context
      command: docker context use {{ compute_context_name }}

    - name: Find s3 image name
      ansible.builtin.shell:
        cmd: docker ps --format json | jq -r ".Names" | grep "{{ s3_container_search_name }}"
      register: s3_image_name

    - name: Verify all backups present
      shell: ./verify-present-on-s3.sh
      register: files_present
      failed_when: files_present.rc == 1
      when: synced_restore == true

    - name: Restore backup - overworld
      ansible.builtin.shell:
        cmd: docker exec "{{s3_image_name.stdout}}" ./restore-backup.sh backup__{{ backup_timestamp }}__overworld.zip
      when: restore_overworld == true

    - name: Restore backup - nether
      ansible.builtin.shell:
        cmd: docker exec "{{s3_image_name.stdout}}" ./restore-backup.sh backup__{{ backup_timestamp }}__nether.zip  
      when: restore_nether == true

    - name: Restore backup - end
      ansible.builtin.shell:
        cmd: docker exec "{{s3_image_name.stdout}}" ./restore-backup.sh backup__{{ backup_timestamp }}__end.zip
      when: restore_end == true

    - name: Return to default context
      ansible.builtin.shell:
        cmd: docker context use default

    - name: Scale up minecraft service
      ansible.builtin.shell:
        cmd: docker service scale {{ minecraft_service_name }}=1